pages:
  image: node:latest
  stage: deploy
  tags:
    - "node"
  script:
    - npm install --progress=false
    - npm run build
    - rm -r -fo public
    - mkdir public
    - cp -r dist/* public
  artifacts:
    expire_in: 1 day
    paths:
      - "public"
  only:
    - master